# Generated by Django 4.0.4 on 2022-07-01 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('picture', models.ImageField(blank=True, upload_to='actors/')),
                ('biographical_summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('picture', models.ImageField(blank=True, upload_to='directors/')),
                ('biographical_summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
                ('year_of_production', models.DateField()),
                ('picture', models.ImageField(blank=True, upload_to='movies/')),
                ('actors', models.ManyToManyField(blank=True, to='sap.actor')),
                ('film_director', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='sap.director')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=60)),
                ('source', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('approved', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.movie')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='nacionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.nacionality'),
        ),
        migrations.AddField(
            model_name='actor',
            name='nacionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.nacionality'),
        ),
    ]
