# Generated by Django 4.0.4 on 2022-07-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('special_status', 'Can create movie')]},
        ),
    ]
