# Generated by Django 4.0.4 on 2022-07-22 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('create_movie', 'Can create movie'), ('update_movie', 'Can update movie'), ('remove_movie', 'Can delete movie')]},
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
