# Generated by Django 4.0.4 on 2022-07-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0005_alter_movie_options_review_disapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
