# Generated by Django 4.0.4 on 2022-05-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('biographical_summary', models.TextField(max_length=300)),
                ('nacionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.nacionality')),
            ],
        ),
    ]
